/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as authenticationAuthenticationImport } from './routes/(authentication)/_authentication'
import { Route as authenticationAuthenticationVerifyImport } from './routes/(authentication)/_authentication.verify'
import { Route as authenticationAuthenticationSignupImport } from './routes/(authentication)/_authentication.signup'
import { Route as authenticationAuthenticationResetPasswordImport } from './routes/(authentication)/_authentication.reset-password'
import { Route as authenticationAuthenticationLoginImport } from './routes/(authentication)/_authentication.login'
import { Route as authenticationAuthenticationForgotPasswordImport } from './routes/(authentication)/_authentication.forgot-password'

// Create Virtual Routes

const authenticationImport = createFileRoute('/(authentication)')()

// Create/Update Routes

const authenticationRoute = authenticationImport.update({
  id: '/(authentication)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authenticationAuthenticationRoute =
  authenticationAuthenticationImport.update({
    id: '/_authentication',
    getParentRoute: () => authenticationRoute,
  } as any)

const authenticationAuthenticationVerifyRoute =
  authenticationAuthenticationVerifyImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => authenticationAuthenticationRoute,
  } as any)

const authenticationAuthenticationSignupRoute =
  authenticationAuthenticationSignupImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => authenticationAuthenticationRoute,
  } as any)

const authenticationAuthenticationResetPasswordRoute =
  authenticationAuthenticationResetPasswordImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => authenticationAuthenticationRoute,
  } as any)

const authenticationAuthenticationLoginRoute =
  authenticationAuthenticationLoginImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => authenticationAuthenticationRoute,
  } as any)

const authenticationAuthenticationForgotPasswordRoute =
  authenticationAuthenticationForgotPasswordImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authenticationAuthenticationRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)': {
      id: '/(authentication)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticationImport
      parentRoute: typeof rootRoute
    }
    '/(authentication)/_authentication': {
      id: '/(authentication)/_authentication'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticationAuthenticationImport
      parentRoute: typeof authenticationRoute
    }
    '/(authentication)/_authentication/forgot-password': {
      id: '/(authentication)/_authentication/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authenticationAuthenticationForgotPasswordImport
      parentRoute: typeof authenticationAuthenticationImport
    }
    '/(authentication)/_authentication/login': {
      id: '/(authentication)/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authenticationAuthenticationLoginImport
      parentRoute: typeof authenticationAuthenticationImport
    }
    '/(authentication)/_authentication/reset-password': {
      id: '/(authentication)/_authentication/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authenticationAuthenticationResetPasswordImport
      parentRoute: typeof authenticationAuthenticationImport
    }
    '/(authentication)/_authentication/signup': {
      id: '/(authentication)/_authentication/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authenticationAuthenticationSignupImport
      parentRoute: typeof authenticationAuthenticationImport
    }
    '/(authentication)/_authentication/verify': {
      id: '/(authentication)/_authentication/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authenticationAuthenticationVerifyImport
      parentRoute: typeof authenticationAuthenticationImport
    }
  }
}

// Create and export the route tree

interface authenticationAuthenticationRouteChildren {
  authenticationAuthenticationForgotPasswordRoute: typeof authenticationAuthenticationForgotPasswordRoute
  authenticationAuthenticationLoginRoute: typeof authenticationAuthenticationLoginRoute
  authenticationAuthenticationResetPasswordRoute: typeof authenticationAuthenticationResetPasswordRoute
  authenticationAuthenticationSignupRoute: typeof authenticationAuthenticationSignupRoute
  authenticationAuthenticationVerifyRoute: typeof authenticationAuthenticationVerifyRoute
}

const authenticationAuthenticationRouteChildren: authenticationAuthenticationRouteChildren =
  {
    authenticationAuthenticationForgotPasswordRoute:
      authenticationAuthenticationForgotPasswordRoute,
    authenticationAuthenticationLoginRoute:
      authenticationAuthenticationLoginRoute,
    authenticationAuthenticationResetPasswordRoute:
      authenticationAuthenticationResetPasswordRoute,
    authenticationAuthenticationSignupRoute:
      authenticationAuthenticationSignupRoute,
    authenticationAuthenticationVerifyRoute:
      authenticationAuthenticationVerifyRoute,
  }

const authenticationAuthenticationRouteWithChildren =
  authenticationAuthenticationRoute._addFileChildren(
    authenticationAuthenticationRouteChildren,
  )

interface authenticationRouteChildren {
  authenticationAuthenticationRoute: typeof authenticationAuthenticationRouteWithChildren
}

const authenticationRouteChildren: authenticationRouteChildren = {
  authenticationAuthenticationRoute:
    authenticationAuthenticationRouteWithChildren,
}

const authenticationRouteWithChildren = authenticationRoute._addFileChildren(
  authenticationRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authenticationAuthenticationRouteWithChildren
  '/forgot-password': typeof authenticationAuthenticationForgotPasswordRoute
  '/login': typeof authenticationAuthenticationLoginRoute
  '/reset-password': typeof authenticationAuthenticationResetPasswordRoute
  '/signup': typeof authenticationAuthenticationSignupRoute
  '/verify': typeof authenticationAuthenticationVerifyRoute
}

export interface FileRoutesByTo {
  '/': typeof authenticationAuthenticationRouteWithChildren
  '/forgot-password': typeof authenticationAuthenticationForgotPasswordRoute
  '/login': typeof authenticationAuthenticationLoginRoute
  '/reset-password': typeof authenticationAuthenticationResetPasswordRoute
  '/signup': typeof authenticationAuthenticationSignupRoute
  '/verify': typeof authenticationAuthenticationVerifyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(authentication)': typeof authenticationRouteWithChildren
  '/(authentication)/_authentication': typeof authenticationAuthenticationRouteWithChildren
  '/(authentication)/_authentication/forgot-password': typeof authenticationAuthenticationForgotPasswordRoute
  '/(authentication)/_authentication/login': typeof authenticationAuthenticationLoginRoute
  '/(authentication)/_authentication/reset-password': typeof authenticationAuthenticationResetPasswordRoute
  '/(authentication)/_authentication/signup': typeof authenticationAuthenticationSignupRoute
  '/(authentication)/_authentication/verify': typeof authenticationAuthenticationVerifyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/(authentication)'
    | '/(authentication)/_authentication'
    | '/(authentication)/_authentication/forgot-password'
    | '/(authentication)/_authentication/login'
    | '/(authentication)/_authentication/reset-password'
    | '/(authentication)/_authentication/signup'
    | '/(authentication)/_authentication/verify'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticationRoute: typeof authenticationRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticationRoute: authenticationRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(authentication)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(authentication)": {
      "filePath": "(authentication)",
      "children": [
        "/(authentication)/_authentication"
      ]
    },
    "/(authentication)/_authentication": {
      "filePath": "(authentication)/_authentication.tsx",
      "parent": "/(authentication)",
      "children": [
        "/(authentication)/_authentication/forgot-password",
        "/(authentication)/_authentication/login",
        "/(authentication)/_authentication/reset-password",
        "/(authentication)/_authentication/signup",
        "/(authentication)/_authentication/verify"
      ]
    },
    "/(authentication)/_authentication/forgot-password": {
      "filePath": "(authentication)/_authentication.forgot-password.tsx",
      "parent": "/(authentication)/_authentication"
    },
    "/(authentication)/_authentication/login": {
      "filePath": "(authentication)/_authentication.login.tsx",
      "parent": "/(authentication)/_authentication"
    },
    "/(authentication)/_authentication/reset-password": {
      "filePath": "(authentication)/_authentication.reset-password.tsx",
      "parent": "/(authentication)/_authentication"
    },
    "/(authentication)/_authentication/signup": {
      "filePath": "(authentication)/_authentication.signup.tsx",
      "parent": "/(authentication)/_authentication"
    },
    "/(authentication)/_authentication/verify": {
      "filePath": "(authentication)/_authentication.verify.tsx",
      "parent": "/(authentication)/_authentication"
    }
  }
}
ROUTE_MANIFEST_END */
